import { build } from "esbuild";
import { PLAN_CSS } from "@planner/engine";
import { writeFile } from "node:fs/promises";

const out = await build({ entryPoints: [new URL("./widget/plan.ts", import.meta.url).pathname], bundle: true, write: false, format: "iife", minify: true, target: "es2022", platform: "browser" });
const js = out.outputFiles[0]!.text.replaceAll("</script", "<\\/script");
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;--rp-floor:#f1ece2;--rp-wall:#1f2a2b;--rp-text:#2a3a3b;--rp-muted:#5a6868;--rp-item:#cfd9d6;--rp-item-big:#b9c9c5;--rp-item-line:#7d9490}
@media (prefers-color-scheme:dark){:root{--rp-floor:#1b2423;--rp-wall:#e9efee;--rp-text:#e9efee;--rp-muted:#9db0ae;--rp-item:#2e4a47;--rp-item-big:#2a4340;--rp-item-line:#6fa39d}}
body{margin:0;padding:12px;font:14px/1.45 system-ui,sans-serif}
.checks{list-style:none;padding:0;margin:10px 0}.checks li{padding:3px 0 3px 22px;position:relative}
.checks li:before{position:absolute;left:0;font-weight:700}.checks .ok:before{content:"\\2713";color:#2c7f52}.checks .no:before{content:"\\2717";color:#b4412f}
button{padding:9px 16px;border-radius:999px;border:0;background:#1f6f6a;color:#fff;font:600 14px system-ui;cursor:pointer}
</style></head><body><div id="root">Planning the layout…</div><script>${js}</script></body></html>`;
await writeFile(new URL("./src/widget.generated.ts", import.meta.url).pathname, `// Generated by build-widget.ts. Do not edit.\nexport const WIDGET_HTML = ${JSON.stringify(html)};\n`);
console.log(`widget: ${(html.length / 1024).toFixed(0)} KB`);
