import { composerSvg, logoSvg, type Glyph } from "./icons.ts";
import type { Files } from "./zip.ts";

export interface PositiveCase { description: string; prompt: string; tools_triggered: string; expected_behavior: string }
export interface NegativeCase { description: string; prompt: string }

/** Everything about a plugin that does not depend on where it is deployed. */
export interface PluginSpec {
  name: string;
  version: string;
  description: string;
  keywords: string[];
  displayName: string;
  shortDescription: string;
  longDescription: string;
  category: string;
  capabilities: string[];
  defaultPrompt: string[];
  server: string;
  glyph: Glyph;
  brand: { light: string; dark: string; darkBg: string; lightBg: string };
  skill: { name: string; description: string; body: string };
  cases: { positive: PositiveCase[]; negative: NegativeCase[] };
  releaseNotes: string;
  countries?: string[];
}
export interface PluginEnv {
  publisher: string;
  email: string;
  siteUrl: string;
  demoUrl?: string;
  repoUrl?: string;
  /** Screenshot PNG files, in order. */
  screenshots: Buffer[];
}

const json = (v: unknown) => Buffer.from(JSON.stringify(v, null, 2) + "\n");

export function buildPluginFiles(spec: PluginSpec, env: PluginEnv): Files {
  const site = env.siteUrl.replace(/\/$/, "");
  const files: Files = new Map();
  files.set("plugin.json", json({
    $schema: "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",
    name: spec.name,
    version: spec.version,
    description: spec.description,
    author: { name: env.publisher, ...(env.email ? { email: env.email } : {}), url: site },
    homepage: site,
    ...(env.repoUrl ? { repository: env.repoUrl } : {}),
    keywords: spec.keywords,
    extensions: {
      "com.openai": {
        interface: {
          displayName: spec.displayName,
          shortDescription: spec.shortDescription,
          longDescription: spec.longDescription,
          developerName: env.publisher,
          category: spec.category,
          capabilities: spec.capabilities,
          websiteURL: site,
          supportURL: `${site}/support/`,
          privacyPolicyURL: `${site}/privacy/`,
          termsOfServiceURL: `${site}/terms/`,
          defaultPrompt: spec.defaultPrompt,
          brandColor: spec.brand.light,
          brandColorDark: spec.brand.dark,
          composerIcon: "./assets/icon.svg",
          composerIconDark: "./assets/icon-dark.svg",
          logo: "./assets/logo.svg",
          logoDark: "./assets/logo-dark.svg",
          screenshots: env.screenshots.map((_, i) => `./assets/screenshot-${i + 1}.png`),
        },
        onboardingSkill: "./skills/get-started/SKILL.md",
        review: {
          test_cases: { positive: spec.cases.positive, negative: spec.cases.negative },
          ...(env.demoUrl ? { demo_recording_url: env.demoUrl } : {}),
          commerce: false,
          commerce_description: "This plugin does not sell products or process payments.",
        },
        publication: { ...(spec.countries ? { countries: spec.countries } : {}), release_notes: spec.releaseNotes },
      },
    },
  }));
  files.set("mcp.json", json({
    $schema: "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json",
    mcpServers: { [spec.server]: { type: "streamable-http", url: `${site}/mcp` } },
  }));
  files.set("skills/get-started/SKILL.md", Buffer.from(`---\nname: ${spec.skill.name}\ndescription: ${spec.skill.description}\n---\n\n${spec.skill.body.trim()}\n`));
  files.set("assets/logo.svg", Buffer.from(logoSvg(spec.glyph, spec.brand.light, "#ffffff")));
  files.set("assets/logo-dark.svg", Buffer.from(logoSvg(spec.glyph, spec.brand.dark, spec.brand.darkBg)));
  files.set("assets/icon.svg", Buffer.from(composerSvg(spec.glyph, spec.brand.light)));
  files.set("assets/icon-dark.svg", Buffer.from(composerSvg(spec.glyph, spec.brand.dark)));
  env.screenshots.forEach((png, i) => files.set(`assets/screenshot-${i + 1}.png`, png));
  files.set("README.md", Buffer.from(`# ${spec.displayName} plugin package\n\nGenerated by \`npm run package:plugins\` in the planner repository. Do not edit by hand; change \`apps/*/plugin/spec.ts\` and rebuild.\n\nUpload the ZIP in the OpenAI Plugins dashboard. The MCP URL (${site}/mcp) cannot be changed after the first upload without support.\n`));
  return files;
}
