import { build } from "esbuild";
import { SEATING_CSS } from "@planner/engine";
import { writeFile } from "node:fs/promises";

const out = await build({ entryPoints: [new URL("./widget/seating.ts", import.meta.url).pathname], bundle: true, write: false, format: "iife", minify: true, target: "es2022", platform: "browser" });
const js = out.outputFiles[0]!.text.replaceAll("</script", "<\\/script");
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;--rp-bg:#fbf7f3;--rp-text:#2a2230;--rp-muted:#675b6c;--rp-item:#efe3e1;--rp-item-line:#b79aa6;--rp-g1:#7b2d5b;--rp-g2:#d98aa6;--rp-g3:#3f8f8a;--rp-g4:#c99a3e;--rp-g5:#6b7fb3}
@media (prefers-color-scheme:dark){:root{--rp-bg:#17121a;--rp-text:#f1e9f1;--rp-muted:#b9a9bd;--rp-item:#2c2233;--rp-item-line:#7d6586;--rp-g1:#d27bb0;--rp-g2:#f0a9c4;--rp-g3:#66c4bd;--rp-g4:#e6c26c;--rp-g5:#94a8de}}
body{margin:0;padding:12px;font:14px/1.45 system-ui,sans-serif}
.checks{list-style:none;padding:0;margin:10px 0}.checks li{padding:3px 0 3px 22px;position:relative}
.checks li:before{position:absolute;left:0;font-weight:700}.checks .ok:before{content:"\\2713";color:#2c7f52}.checks .no:before{content:"\\2717";color:#b4412f}
button{padding:9px 16px;border-radius:999px;border:0;background:#7b2d5b;color:#fff;font:600 14px system-ui;cursor:pointer}
</style></head><body><div id="root">Building the seating chart…</div><script>${js}</script></body></html>`;
await writeFile(new URL("./src/widget.generated.ts", import.meta.url).pathname, `// Generated by build-widget.ts. Do not edit.\nexport const WIDGET_HTML = ${JSON.stringify(html)};\n`);
console.log(`widget: ${(html.length / 1024).toFixed(0)} KB`);
